# .github/workflows/typescript.yml
name: TypeScript Client

on:
  push:
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript.yml'
    branches: [ main, ts ]
  pull_request:
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript.yml'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript

    steps:
    - uses: actions/checkout@v4
    
    # Initial clean npm install to generate package-lock.json
    - name: Initialize npm
      run: |
        npm install --package-lock-only --no-audit
        git status
    
    # Now setup Node with caching
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        cache-dependency-path: './typescript/package-lock.json'
        
    - name: Install dependencies
      run: npm ci --prefer-offline
        
    - name: Type check
      run: npm run type-check
        
    - name: Lint
      run: npm run lint
        
    - name: Test
      run: npm run test
        
    - name: Build
      run: npm run build
    
    # Only run publish step on releases with a tag starting with 'ts-v'
    - name: Publish to npm
      if: startsWith(github.ref, 'refs/tags/ts-v')
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
